#ifndef _IRCODES_H_
#define _IRCODES_H_

#define NC_IR_UP     0xFF629D // KEYES UP
#define NC_IR_DOWN   0xFFA857 // KEYES DOWN
#define NC_IR_LEFT   0xFF22DD // KEYES LEFT
#define NC_IR_RIGHT  0xFFC23D // KEYES RIGHT
#define NC_IR_UP2    0xFF9867 // KEYES 2
#define NC_IR_DOWN2  0xFF30CF // KEYES 4
#define NC_IR_LEFT2  0xFF7A85 // KEYES 6
#define NC_IR_RIGHT2 0xFF38C7 // KEYES 8

#define NC_IR_JOY1   0xFF42BD // KEYES STAR
#define NC_IR_JOY2   0xFF52AD // KEYES SHARP

#define NC_IR_START  0xFF4AB5 // KEYES 0
#define NC_IR_SELECT 0xFF02FD // KEYES OK

#define NC_IR_A      0xFF6897 // KEYES 1
#define NC_IR_B      0xFFB04F // KEYES 3
#define NC_IR_C      0xFF18E7 // KEYES 5
#define NC_IR_D      0xFF10EF // KEYES 7

#define NC_IR_REPEAT 0xFFFFFFFF // KEYES REPEAT

#endif

